apiVersion: v1
kind: Pod
metadata:
  name: broken-init-pod
spec:
  initContainers:
    - name: failing-init
      image: busybox
      command: ["sh", "-c", "echo 'Init failing!' && exit 1"]  # always fails
  containers:
    - name: main-app
      image: nginx
